version: "3.3"
services:
  mysql:
    image: baijunyao/mysql
    container_name: laravel-bjyblog-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=laravel_bjyblog
      - MYSQL_DATABASE=laravel_bjyblog
      - MYSQL_USER=laravel-bjyblog
      - MYSQL_PASSWORD=laravel_bjyblog
    volumes:
      - mysql:/var/lib/mysql

  nginx:
    image: baijunyao/nginx
    container_name: laravel-bjyblog-nginx
    volumes:
      - .:/app
      - ./docker/nginx/laravel-bjyblog.conf:/etc/nginx/conf.d/laravel-bjyblog.conf
    ports:
      - "8082:80"

  php:
    image: baijunyao/php:${APP_ENV}
    container_name: laravel-bjyblog-php
    tty: true
    volumes:
      - .:/app

volumes:
  mysql: