apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: blog
data:
  config: |
    server {
        listen       80;
        server_name  {{ .Values.host }};
        root   /app/public;
        index  index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp)$ {
            expires 30d;
            access_log off;
            add_header Cache-Control public;
        }

        location ~ .*\.(js|css)?$ {
            expires 1d;
            access_log off;
            add_header Cache-Control public;
        }
    }

{{- if .Values.oss.enabled }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ossutil-config
  namespace: blog
data:
  config: |
    [Credentials]
    language=EN
    endpoint={{ .Values.oss.endpoint }}
    accessKeyID={{ .Values.oss.access_key_id }}
    accessKeySecret={{ .Values.oss.access_key_secret }}
{{- end }}
