apiVersion: v1
kind: Namespace
metadata:
  name: blog

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-pv
  labels:
    pv: code-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/laravel-bjyblog"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  namespace: blog
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: code-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    pv: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/mysql"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: blog
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mysql-pv

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  labels:
    pv: backup-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/backup"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: blog
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: backup-pv

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.0

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: blog
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: baijunyao/mysql:8.0-production
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: laravel_bjyblog
            - name: MYSQL_DATABASE
              value: laravel_bjyblog
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: laravel_bjyblog
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pvc
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: blog
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: baijunyao/php:7.4-production
          volumeMounts:
            - mountPath: /app
              name: code-pvc
      volumes:
        - name: code-pvc
          persistentVolumeClaim:
            claimName: code-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: blog
  labels:
    app: php
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: php

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: blog
data:
  config: |
    server {
        listen       80;
        server_name  baijunyao.com;
        root   /app/public;
        index  index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: code-pvc
          persistentVolumeClaim:
            claimName: code-pvc
        - name: config
          configMap:
            name: nginx-config
            items:
              - key: config
                path: laravel-bjyblog.conf
      containers:
        - name: nginx
          image: baijunyao/nginx:1.7
          volumeMounts:
            - name: code-pvc
              mountPath: /app
            - name: config
              mountPath: /etc/nginx/conf.d

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: blog
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: blog
spec:
  rules:
    - host: baijunyao.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: generate-sitemap
  namespace: blog
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: php
              image: baijunyao/php:7.4-production
              command: ["php", "artisan", "bjyblog:generate-sitemap"]
              volumeMounts:
                - mountPath: /app
                  name: code-pvc
          volumes:
            - name: code-pvc
              persistentVolumeClaim:
                claimName: code-pvc
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: database-backup
  namespace: blog
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: database-backup
              image: baijunyao/mysql-client:1.0
              command: ["/bin/sh", "-c", "/usr/bin/mysqldump -hmysql-service -uroot -plaravel_bjyblog laravel_bjyblog > /backup/laravel_bjyblog_`date +%Y%m%d`.sql"]
              volumeMounts:
                - mountPath: /backup
                  name: backup-pvc
                  subPath: database
          volumes:
            - name: backup-pvc
              persistentVolumeClaim:
                claimName: backup-pvc
          restartPolicy: Never

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: site-backup
  namespace: blog
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: site-backup
              image: busybox:1.32
              command: ["/bin/sh", "-c", "/bin/tar -czvf /backup/laravel_bjyblog_`date +%Y%m%d`.tar.gz /app"]
              volumeMounts:
                - mountPath: /backup
                  name: backup-pvc
                  subPath: site
                - mountPath: /app
                  name: code-pvc
          volumes:
            - name: backup-pvc
              persistentVolumeClaim:
                claimName: backup-pvc
            - name: code-pvc
              persistentVolumeClaim:
                claimName: code-pvc
          restartPolicy: Never
